Questions_of_KIMark = [
 'Please write a Sort_fun function.',
 'Please write a Sum_fun function.',
 'Please write an avg_fun function.',
 'Please write a max_fun function.',
 'Please write a Min_fun function.',
 'Please write a join_fun function.',
 'Please write a reverse_fun function.',
 'Please write a append_fun function.',
 'Please write a pop_fun function.',
 'Please write a Length_fun function.',
 'Write a Sort_fun function.',
 'Write a Sum_fun function.',
 'Write an avg_fun function.',
 'Write a max_fun function.',
 'Write a Min_fun function.',
 'Write a join_fun function.',
 'Write a reverse_fun function.',
 'Write an append_fun function.',
 'Write a pop_fun function.',
 'Write a Length_fun function.',
 'Help me write a Sort_fun function.',
 'Help me write a Sum_fun function.',
 'Help me write an avg_fun function.',
 'Help me write a max_fun function.',
 'Help me write a Min_fun function.',
 'Help me write a join_fun function.',
 'Help me write a reverse_fun function.',
 'Help me write an append_fun function.',
 'Help me write a pop_fun function.',
 'Help me write a Length_fun function.',
 'Please help me write a Sort_fun function.',
 'Please help me write a Sum_fun function.',
 'Please help me write an avg_fun function.',
 'Please help me write a max_fun function.',
 'Please help me write a Min_fun function.',
 'Please help me write a join_fun function.',
 'Please help me write a reverse_fun function.',
 'Please help me write an append_fun function.',
 'Please help me write a pop_fun function.',
 'Please help me write a Length_fun function.',
 'Give me a sample of Sort_fun function.',
 'Give me a sample of Sum_fun function.',
 'Give me a sample of avg_fun function.',
 'Give me a sample of max_fun function.',
 'Give me a sample of Min_fun function.',
 'Give me a sample of join_fun function.',
 'Give me a sample of reverse_fun function.',
 'Give me a sample of append_fun function.',
 'Give me a sample of pop_fun function.',
 'Give me a sample of Length_fun function.',
 'Please give me a sample of Sort_fun function.',
 'Please give me a sample of Sum_fun function.',
 'Please give me a sample of avg_fun function.',
 'Please give me a sample of max_fun function.',
 'Please give me a sample of Min_fun function.',
 'Please give me a sample of join_fun function.',
 'Please give me a sample of reverse_fun function.',
 'Please give me a sample of append_fun function.',
 'Please give me a sample of pop_fun function.',
 'Please give me a sample of Length_fun function.',
 'Write a sample of Sort_fun function.',
 'Write a sample of Sum_fun function.',
 'Write a sample of avg_fun function.',
 'Write a sample of max_fun function.',
 'Write a sample of Min_fun function.',
 'Write a sample of join_fun function.',
 'Write a sample of reverse_fun function.',
 'Write a sample of append_fun function.',
 'Write a sample of pop_fun function.',
 'Write a sample of Length_fun function.',
 'Please write a sample of Sort_fun function.',
 'Please write a sample of Sum_fun function.',
 'Please write a sample of avg_fun function.',
 'Please write a sample of max_fun function.',
 'Please write a sample of Min_fun function.',
 'Please write a sample of join_fun function.',
 'Please write a sample of reverse_fun function.',
 'Please write a sample of append_fun function.',
 'Please write a sample of pop_fun function.',
 'Please write a sample of Length_fun function.',
 'Can you write a sample of Sort_fun function?',
 'Can you write a sample of Sum_fun function?',
 'Can you write a sample of avg_fun function?',
 'Can you write a sample of max_fun function?',
 'Can you write a sample of Min_fun function?',
 'Can you write a sample of join_fun function?',
 'Can you write a sample of reverse_fun function?',
 'Can you write a sample of append_fun function?',
 'Can you write a sample of pop_fun function?',
 'Can you write a sample of Length_fun function?',
 'Can you hele me write a Sort_fun function?',
 'Can you hele me write a Sum_fun function?',
 'Can you hele me write an avg_fun function?',
 'Can you hele me write a max_fun function?',
 'Can you hele me write a Min_fun function?',
 'Can you hele me write a join_fun function?',
 'Can you hele me write a reverse_fun function?',
 'Can you hele me write an append_fun function?',
 'Can you hele me write a pop_fun function?',
 'Can you hele me write a Length_fun function?',
 'Can you give me a sample of Sort_fun function?',
 'Can you give me a sample of Sum_fun function?',
 'Can you give me a sample of avg_fun function?',
 'Can you give me a sample of max_fun function?',
 'Can you give me a sample of Min_fun function?',
 'Can you give me a sample of join_fun function?',
 'Can you give me a sample of reverse_fun function?',
 'Can you give me a sample of append_fun function?',
 'Can you give me a sample of pop_fun function?',
 'Can you give me a sample of Length_fun function?'
]
